name: Python Flask App Workflow

on:
  push:
    branches:
      - main  # or the branch you want to trigger the action

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify Python 3.10

    - name: Print Python version and pip list
      run: |
        python --version
        pip list

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Print installed packages
      run: pip list

    - name: Run tests
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        # Run your tests here
        # For example: python -m unittest discover tests

    - name: Check Flask app starts
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        export FLASK_APP=app.py
        # Start Flask app in the background
        flask run &
        # Wait for the app to start
        sleep 5
        # Check if the app is running
        curl http://localhost:5000 || exit 1
        # Stop the Flask app
        kill %1

    # Add deployment steps here if needed